// <auto-generated />
using System;
using Acoes_Fiis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acoes_Fiis.Migrations
{
    [DbContext(typeof(Acoes_FiisContext))]
    [Migration("20260610233913_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acoes_Fiis.Models.AporteExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MesReferencia")
                        .HasColumnType("integer");

                    b.Property<int>("PriceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.ToTable("AportesExtras");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.AtivoGeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasseAtivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AtivosGerais");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxaRentabilidade")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAtivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Carteira");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.ConfiguracaoBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoPastaLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervaloHoras")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoBackup")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesBackup");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.ContaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ContasFixas");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.EvolucaoPatrimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MesAno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("EvolucaoPatrimonial");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pagamento")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ControleFinanceiro");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.FolhaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Descontos")
                        .HasColumnType("numeric");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("PathPdf")
                        .HasColumnType("text");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("numeric");

                    b.Property<string>("Visao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FolhasPagamento");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.HistoricoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoUnidade")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HistoricoAtivos");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.MetaAlocacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PercentualAlvo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MetasAlocacao");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CdiAnual")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AporteExtraMensal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxaJurosAnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorEntrada")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorImovel")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorPrestação")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Financiamentos");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Recomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Roe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAtivo")
                        .HasColumnType("text");

                    b.Property<decimal>("VPA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Recomendacoes");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.RecomendacaoFii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoFii")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UltimoRendimento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("VPA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Vacancia")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("RecomendacoesFii");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.AporteExtra", b =>
                {
                    b.HasOne("Acoes_Fiis.Models.Price", "Price")
                        .WithMany("AportesPontuais")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Price", b =>
                {
                    b.Navigation("AportesPontuais");
                });
#pragma warning restore 612, 618
        }
    }
}
