// <auto-generated />
using System;
using Acoes_Fiis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acoes_Fiis.Migrations
{
    [DbContext(typeof(Acoes_FiisContext))]
    partial class Acoes_FiisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Acoes_Fiis.Models.AporteExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.ToTable("AportesExtras");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.AtivoGeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseAtivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AtivosGerais");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Setor")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaRentabilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carteira");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.ContaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasFixas");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ControleFinanceiro");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AporteExtraMensal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxaJurosAnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorEntrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorImovel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPrestação")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Financiamentos");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Recomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Roe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtivo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VPA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Recomendacoes");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.RecomendacaoFii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFii")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UltimoRendimento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("VPA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Vacancia")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("RecomendacoesFii");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.AporteExtra", b =>
                {
                    b.HasOne("Acoes_Fiis.Models.Price", "Price")
                        .WithMany("AportesPontuais")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Acoes_Fiis.Models.Price", b =>
                {
                    b.Navigation("AportesPontuais");
                });
#pragma warning restore 612, 618
        }
    }
}
